// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkgdvthbwryjwvbabxjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZ2R2dGhid3J5and2YmFieGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM5OTksImV4cCI6MjA2MDIyOTk5OX0.EwZ13gh-i_LVsYjIIA0UPBnymWnBmjY3f2mrtmnFVCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);